- hosts: all
  sudo: True

  tasks:
    - yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
    - yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-kilo/rdo-release-kilo-1.noarch.rpm state=present
      when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

    - include_vars: settings.yaml
    - yum: name={{item}}
      with_items:
        - openstack-utils
        - python-swiftclient
        - memcached
        - rsync
        - xinetd
        - openstack-swift
        - openstack-swift-proxy
        - openstack-swift-object
        - openstack-swift-container
        - openstack-swift-account

    - lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=Permissive

    - command: /usr/sbin/setenforce Permissive

    - copy: src=files/etc/sysctl.d/swift.conf dest=/etc/sysctl.d/swift.conf

    - command: /usr/sbin/sysctl -p

    - template: dest=/etc/swift/{{ item }} src=files/etc/swift/{{ item }} owner=swift group=swift
      with_items:
        - object-server/1.conf
        - object-server/2.conf
        - object-server/3.conf
        - object-server/4.conf
        - container-server/1.conf
        - container-server/2.conf
        - container-server/3.conf
        - container-server/4.conf
        - account-server/1.conf
        - account-server/2.conf
        - account-server/3.conf
        - account-server/4.conf
        - container-reconciler.conf
        - object-expirer.conf
        - proxy-server.conf
        - swift.conf

    - file: path=/etc/swift/{{item}} state=absent
      with_items:
        - account-server.conf
        - container-server.conf
        - object-server.conf

    - file: path=/etc/swift/ state=directory owner=swift group=swift recurse=yes

    - file: path=/srv  state=directory

    - file: path={{ item }} state=directory owner=swift group=swift
      with_items:
        - /srv/1/node/{{ block_device }}1
        - /srv/2/node/{{ block_device }}2
        - /srv/3/node/{{ block_device }}3
        - /srv/4/node/{{ block_device }}4
        - /var/run/swift
        - /var/cache/swift
        - /var/cache/swift2
        - /var/cache/swift3
        - /var/cache/swift4

    - script: files/bin/remakerings {{ block_device }} creates=/etc/swift/object.ring.gz

    - service: name={{item}} state=started enabled=yes
      with_items:
        - memcached
        - xinetd
        - rsyncd

    # Make sure Swift services are disabled. Swift must be started with
    # swift-init (see below) to make use of the [1..4].conf files
    - service: name={{item}} state=stopped enabled=no
      with_items:
        - openstack-swift-account-auditor
        - openstack-swift-account-reaper
        - openstack-swift-account-replicator
        - openstack-swift-account
        - openstack-swift-container-auditor
        - openstack-swift-container-reconciler
        - openstack-swift-container-replicator
        - openstack-swift-container
        - openstack-swift-container-updater
        - openstack-swift-object-auditor
        - openstack-swift-object-expirer
        - openstack-swift-object-replicator
        - openstack-swift-object
        - openstack-swift-object-updater
        - openstack-swift-proxy

    - command: /usr/bin/swift-init start all creates=/var/run/swift/proxy-server.pid
