- hosts: all
  sudo: True

  tasks:
    - include_vars: settings.yaml

    - dnf: name=yum  # Workaround
      when: ansible_distribution == 'Fedora' and ansible_distribution_version >= 22

    - get_url: url=https://grafanarel.s3.amazonaws.com/builds/grafana-2.5.0-1.x86_64.rpm dest=/root/grafana-2.5.0-1.x86_64.rpm mode=0440

    - yum: name={{item}}
      with_items:
        - memcached
        - graphite-web
        - python-carbon
        - python-whisper
        - statsd
        - collectd
        - /root/grafana-2.5.0-1.x86_64.rpm

    - lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=Permissive

    - command: /usr/sbin/setenforce Permissive

    - template: dest=/etc/carbon/storage-schemas.conf src=files/etc/carbon/storage-schemas.conf

    - template: dest=/etc/statsd/config.js src=files/etc/statsd/config.js

    - template: dest=/etc/graphite-web/local_settings.py src=files/etc/graphite-web/local_settings.py

    - file: path=/opt/graphite/storage/ state=directory owner=apache group=apache

    - command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput creates=/opt/graphite/storage/graphite.db

    - file: path=/opt/graphite/storage/graphite.db owner=apache group=apache

    - copy: src=files/dashboard.json dest=/tmp/dashboard.json

    - service: name={{item}} state=started
      with_items:
        - memcached
        - statsd
        - carbon-cache
        - httpd
        - grafana-server

    - shell: curl -X POST --data-urlencode state@/tmp/dashboard.json http://127.0.0.1/dashboard/save/default
