- hosts: all
  remote_user: fedora
  sudo: True

  tasks:
    - include_vars: settings.yaml
    - yum: name={{item}}
      with_items:
        - openstack-utils
        - python-swiftclient
        - memcached
        - rsync
        - xinetd
        - openstack-swift
        - openstack-swift-proxy
        - openstack-swift-object
        - openstack-swift-container
        - openstack-swift-account
        - graphite-web
        - graphite-web-selinux
        - python-carbon
        - python-whisper
        - statsd
        - collectd

    - lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=Permissive

    - command: /usr/sbin/setenforce Permissive

    - copy: src=files/etc/sysctl.d/swift.conf dest=/etc/sysctl.d/swift.conf

    - command: /usr/sbin/sysctl -p

    - template: dest=/etc/swift/{{ item }} src=files/etc/swift/{{ item }} owner=swift group=swift
      with_items:
        - object-server/1.conf
        - object-server/2.conf
        - object-server/3.conf
        - object-server/4.conf
        - container-server/1.conf
        - container-server/2.conf
        - container-server/3.conf
        - container-server/4.conf
        - account-server/1.conf
        - account-server/2.conf
        - account-server/3.conf
        - account-server/4.conf
        - container-reconciler.conf
        - object-expirer.conf
        - proxy-server.conf
        - swift.conf

    - file: path=/etc/swift/{{item}} state=absent
      with_items:
        - account-server.conf
        - container-server.conf
        - object-server.conf

    - file: path=/etc/swift/ state=directory owner=swift group=swift recurse=yes

    - file: path=/srv  state=directory

    - file: path={{ item }} state=directory owner=swift group=swift
      with_items:
        - /srv/1/node/sdb1
        - /srv/2/node/sdb2
        - /srv/3/node/sdb3
        - /srv/4/node/sdb4
        - /var/run/swift
        - /var/cache/swift
        - /var/cache/swift2
        - /var/cache/swift3
        - /var/cache/swift4
        # Make sure at least one quarantined dir exists
        # otherwise collectd won't report anything
        - /srv/1/node/sdb1/quarantined/accounts
        - /srv/1/node/sdb1/quarantined/containers
        - /srv/1/node/sdb1/quarantined/objects

    - script: files/bin/remakerings creates=/etc/swift/object.ring.gz

    - template: dest=/etc/carbon/storage-schemas.conf src=files/etc/carbon/storage-schemas.conf

    - template: dest=/etc/statsd/config.js src=files/etc/statsd/config.js

    - template: dest=/etc/collectd.conf src=files/etc/collectd.conf
      notify:
        - restart collectd

    - copy: src=files/dashboard.json dest=/tmp/dashboard.json

    - template: dest=/etc/graphite-web/local_settings.py src=files/etc/graphite-web/local_settings.py

    - file: path=/opt/graphite/storage/ state=directory owner=apache group=apache

    - command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput creates=/opt/graphite/storage/graphite.db

    - file: path=/opt/graphite/storage/graphite.db owner=apache group=apache

    - shell: curl -X POST --data-urlencode state@dashboard.json http://127.0.0.1/dashboard/save/default

    - service: name={{item}} state=started
      with_items:
        - memcached
        - xinetd
        - rsyncd
        - statsd
        - carbon-cache
        - httpd
        - collectd

    - command: /usr/bin/swift-init start all creates=/var/run/swift/proxy-server.pid

  handlers:
    - name: restart collectd
      service: name=collectd state=restarted
