- hosts: all
  remote_user: fedora
  sudo: True

  tasks:
    - include_vars: settings.yaml
    - yum: name={{item}}
      with_items:
        - xfsprogs
        - openstack-utils
        - python-swiftclient
        - memcached
        - rsync
        - xinetd
        - openstack-swift
        - openstack-swift-proxy
        - openstack-swift-object
        - openstack-swift-container
        - openstack-swift-account
        - graphite-web
        - graphite-web-selinux
        - python-carbon
        - python-whisper
        - statsd
        - collectd

    - lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=Permissive

    - command: /usr/sbin/setenforce Permissive

    - copy: src=filesetc/sysctl.d/swift.conf dest=/etc/sysctl.d/swift.conf

    - command: /usr/sbin/sysctl -p

    - template: dest=/etc/swift/{{ item }} src=files/etc/swift/{{ item }} owner=swift group=swift
      with_items:
        - object-server/1.conf
        - object-server/2.conf
        - object-server/3.conf
        - object-server/4.conf
        - container-server/1.conf
        - container-server/2.conf
        - container-server/3.conf
        - container-server/4.conf
        - account-server/1.conf
        - account-server/2.conf
        - account-server/3.conf
        - account-server/4.conf
        - container-reconciler.conf
        - object-expirer.conf
        - proxy-server.conf
        - swift.conf

    - file: path=/etc/swift/{{item}} state=absent
      with_items:
        - account-server.conf
        - container-server.conf
        - object-server.conf

    - file: path=/opt/graphite/storage/ state=directory owner=apache group=apache

    - command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput creates=/opt/graphite/storage/graphite.db

    - file: path=/opt/graphite/storage/graphite.db owner=apache group=apache

    - file: path=/etc/swift/ state=directory owner=swift group=swift recurse=yes

    - file: path=/srv  state=directory

    - command: /usr/bin/truncate -s 1GB /srv/swift-disk-{{item}} creates=/srv/swift-disk-{{item}}
      with_sequence: start=1 end=4

    - command: /usr/sbin/mkfs.xfs /srv/swift-disk-{{item}}
      with_sequence: start=1 end=4
      ignore_errors: yes

    - file: path={{ item }} state=directory owner=swift group=swift
      with_items:
        - /srv/1/node/sdb1
        - /srv/2/node/sdb2
        - /srv/3/node/sdb3
        - /srv/4/node/sdb4
        - /var/run/swift
        - /var/cache/swift
        - /var/cache/swift2
        - /var/cache/swift3
        - /var/cache/swift4
        # Make sure at least one quarantined dir exists
        # otherwise collectd won't report anything
        - /srv/1/node/sdb1/quarantined/accounts
        - /srv/1/node/sdb1/quarantined/containers
        - /srv/1/node/sdb1/quarantined/objects

    - mount: src=/srv/swift-disk-{{item}} name=/srv/{{item}}/node/sdb{{item}} fstype=xfs opts=loop,noatime,nodiratime,nobarrier,logbufs=8 state=mounted
      with_sequence: start=1 end=4

    - file: path=/srv/{{item}}/node/sdb{{item}} state=directory owner=swift group=swift
      with_sequence: start=1 end=4

    - script: files/bin/remakerings creates=/etc/swift/object.ring.gz

    - copy: src=files/dashboard.sql dest=/tmp/dashboard.sql

    - shell: sqlite3 /opt/graphite/storage/graphite.db < /tmp/dashboard.sql ; exit 0

    - service: name={{item}} state=started
      with_items:
        - memcached
        - xinetd
        - rsyncd
        - statsd
        - carbon-cache
        - httpd
        - collectd

    - command: /usr/bin/swift-init start all creates=/var/run/swift/proxy-server.pid
